# Generated by Django 4.2.7 on 2023-11-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, default='hi'),
            preserve_default=False,
        ),
    ]
